---
- name: "create a user for Prometheus Node Exporter"
  become: true
  shell: |
    useradd --no-create-home node_exporter

- name: "install Node Exporter binaries"
  become: true
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "configure a service"
  template:
    src: files/node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: "configure systemd"
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter
    sudo systemctl status node-exporter