---
- name: Extract artifact.tar.gz into ~/
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "start app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start