---
- name: Extract artifact.tar.gz into ~/web
  ansible.builtin.unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: "start app"
  shell: |
    cd ~/web
    npm install
    pm2 stop default
    pm2 start npm -- start