---
- name: "extract artifact.tar.gz into ~/"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "make .env file"
  shell: |
    echo "TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" > .env
    echo "TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> .env
    echo "TYPEORM_HOST=${TYPEORM_HOST}" >> .env
    echo "TYPEORM_PORT=${TYPEORM_PORT}" >> .env
    echo "TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> .env
    echo "TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> .env
    echo "TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> .env
    echo "TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> .env
    echo "TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> .env

- name: "start app"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start