---
- name: Extract artifact.tar.gz into /var/www
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /var/www

- name: "start app"
  shell: |
    cd /var/www
    npm install
    pm2 stop default
    pm2 start npm -- start